# This is the default configuration file for Eradiate.
# See the documentation for a description of all entries.

azimuth_convention = "east_right"
data_store_url = "https://eradiate.eu/data/store/"
offline = false
progress = "spectral_loop"
small_files_registry_revision = "master"
small_files_registry_url = "https://raw.githubusercontent.com/eradiate/eradiate-data"

[absorption_database.error_handling]
# Atmospheric pressure easily goes very low, but at these altitude, the air is
# very thin and so is the absorption coefficient ⇒ ignore ouf-of-bounds errors
p = {missing = "raise", scalar = "raise", bounds = "ignore"}
# Atmospheric temperature climbs fast above 80-100 km, but at these altitude,
# the air is very thin and so is the absorption coefficient
t = {missing = "raise", scalar = "raise", bounds = "ignore"}
# Ignore missing molecule coordinates, and raise when going out of the
# covered range
x = {missing = "ignore", scalar = "ignore", bounds = "raise"}
