channels:
  - eradiate
  - conda-forge
  - defaults
dependencies:
  # recommended
  - aabbtree
  - astropy>=6.0.0
  - ipython
  - ipywidgets
  - jupyterlab
  - python-dateutil
  - python-graphviz
  - seaborn
