[tool.isort]
profile = "black"
reverse_relative = true

[tool.coverage.run]
source = [
    "eradiate/",
]
omit = [
    "*/tests/*",
]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    # Ignore this warning issued by outdated dependencies
    "ignore:distutils Version classes are deprecated:DeprecationWarning",
]
