[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
version_scheme = "post-release"  # Count commits since last tag, don't anticipate new version
git_describe_command = [
    "git",
    "describe",
    "--dirty",
    # "--tags",
    "--long",
    "--match",
    "*[0-9]*",
]  # Redefined to avoid crashing with special build tags

[tool.isort]
profile = "black"
reverse_relative = true

[tool.coverage.run]
source = [
    "eradiate/",
]
omit = [
    "*/tests/*",
]

[tool.pytest.ini_options]
filterwarnings = [
    "error",
    # Ignore these warnings issued by outdated dependencies
    "ignore:distutils Version classes are deprecated:DeprecationWarning",
]
