[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61", "setuptools_scm>=6.2"]

[project]
authors = [
  {name = "The Eradiate Team"},
]
description = "A radiative transfer model for the Earth observation community"
dynamic = ["version"]
license = {text = "LGPLv3"}
maintainers = [
  {name = "The Eradiate Team"},
]
name = "eradiate"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "aenum",
  "attrs>=21.4",
  "click",
  "dessinemoi>=22.2.0",
  "environ-config",
  "matplotlib",
  "netcdf4",
  "numpy",
  "pint",
  "pinttrs>=21.3.0",
  "pooch",
  "rich",
  "ruamel.yaml",
  "scipy",
  "tqdm",
  "xarray>=0.19,!=0.20.*",
]

[project.optional-dependencies]
recommended = [
  "aabbtree",  # Used by the leaf collision detection feature
  "astropy",  # Used by the Solar irradiance spectrum date-based scaling feature
  "iapws",  # Used by thermophysical property utilities
  "ipython",
  "ipywidgets",
  "jupyterlab",
  "python-dateutil",  # Used by the Solar irradiance spectrum date-based scaling feature
  "seaborn",  # Used to define the Eradiate plotting style
]

tests = [
  "pytest",
  "pytest-json-report",
]

dev = [
  "conda-lock>=0.12",  # Required by dependency management scripts
  "pip>=22",  # Required by dependency management scripts
  "pip-tools>=6.5",  # Required by dependency management scripts
  "setuptools>=61",  # Required by dependency management scripts
]

docs = [
  "autodocsumm",
  "myst-parser",
  "nbsphinx",
  "sphinx-book-theme>=0.1.10",
  "sphinx>=3.1",
  "sphinxcontrib-bibtex>=2.0",
  "sphinx-autobuild",
  "sphinx-click>=3.0.2",
  "sphinx-copybutton",
  "sphinx-design",
]

[project.urls]
changelog = "https://github.com/eradiate/eradiate/CHANGELOG.md"
documentation = "https://eradiate.readthedocs.io"
repository = "https://github.com/eradiate/eradiate"

[project.scripts]
eradiate = "eradiate.cli:main"
ertdata = "eradiate.cli:data"
ertshow = "eradiate.cli:show"

[tool.setuptools.packages.find]
exclude = ["plugins"]
include = ["eradiate*"]
namespaces = false
where = ["src"]

[tool.setuptools_scm]
git_describe_command = [
  "git",
  "describe",
  "--dirty", # "--tags",
  "--long",
  "--match",
  "v[0-9]*",
] # Redefined to avoid crashing with special build tags
version_scheme = "post-release" # Count commits since last tag, don't anticipate new version

[tool.isort]
profile = "black"
reverse_relative = true

[tool.coverage.run]
omit = [
  "*/tests/*",
]
source = [
  "eradiate/",
]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore:distutils Version classes are deprecated:DeprecationWarning",
  # Remove the following when environment issues are solved
  "ignore:numpy.ndarray size changed, may indicate binary incompatibility:RuntimeWarning",
]
testpaths = "tests"
