name: eradiate_nested
channels:
  - default
dependencies:
  - python=3.7
  - attrs
  - ipython
  - jupyter
  - lxml
  - matplotlib
  - numpy
  - pint
  - pip
  - pytest 
  - pytest-xdist
  - pyyaml
  - scipy
  - sphinx>=2.4
  # Optional deps
  - pip:
    - guzzle_sphinx_theme
    - sphinxcontrib-bibtex