mode: mono
surface:
  type: lambertian
  reflectance:
    type: uniform
    value: 0.5  # dimensionless
atmosphere:
  type: homogeneous
  toa_altitude: 40.  # km
illumination:
  type: directional
  zenith: 30.  # deg
  azimuth: 0.  # deg
  irradiance:
    type: uniform
    value: 1.8e+6  # W/km^2/nm
measures:
  - type: distant
    id: toa_hsphere
    spectral_cfg:
      wavelength: 550.  # nm
    spp: 32000  # dimensionless
