mode:
  type: mono
  wavelength: 550.  # nm
surface:
  type: lambertian
  reflectance:
    type: uniform
    value: 0.5
atmosphere:
  type: homogeneous
  toa_altitude: 40.
  toa_altitude_units: km
illumination:
  type: directional
  zenith: 30.0
  zenith_units: deg
  azimuth: 0.0
  azimuth_units: deg
  irradiance:
    type: solar_irradiance
measures:
  - type: distant
    id: toa_hsphere
    orientation: 0.0
    orientation_units: deg
    film_resolution: [32, 32]
    spp: 100000
