channels:
  - eradiate
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  # main
  - aabbtree
  - attrs
  - click
  - cerberus
  - dask
  - dessinemoi
  - environ-config
  - iapws
  - matplotlib
  - netcdf4
  - numpy
  - pint
  - pinttrs>=21.3.0
  - rich
  - ruamel.yaml
  - scipy
  - tqdm
  - xarray
  # tests
  - pytest
  - pytest-json-report
  - pytest-metadata
  - pytest-xdist
  - rst2pdf
  - sphinx
  - tabulate
  # dev
  - black
  - bump2version
  - conda-lock>=0.12
  - coverage
  - ipython
  - ipywidgets
  - isort
  - jupyterlab
  - pip
  - pip-tools
  - setuptools
  - twine
  # docs
  - mock
  - sphinx-book-theme
  - sphinx>=3.1
  - sphinxcontrib-bibtex>=2.0
  - sphinx-copybutton
  - sphinx-gallery
  - sphinx-panels
  - tinydb
