channels:
  - eradiate
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # main
  - aenum
  - attrs>=22.2
  - click
  - dessinemoi>=23.1.0
  - environ-config
  - matplotlib>=3.3
  - netcdf4
  - numpy
  - pint
  - pinttrs>=23.2.0
  - pooch
  - rich
  - ruamel.yaml
  - scipy
  - tqdm
  - xarray>=0.19,!=0.20.*
  # recommended
  - aabbtree
  - astropy
  - iapws
  - ipython
  - ipywidgets
  - jupyterlab
  - python-dateutil
  - seaborn
