channels:
  - eradiate
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # main
  - aenum
  - attrs>=21.4
  - click
  - dessinemoi>=22.2.0
  - environ-config
  - matplotlib
  - netcdf4
  - numpy
  - pint
  - pinttrs>=21.3.0
  - pooch
  - rich
  - ruamel.yaml
  - scipy
  - tqdm
  - xarray>=0.19,!=0.20.*
  # recommended
  - aabbtree
  - astropy
  - iapws
  - ipython
  - ipywidgets
  - jupyterlab
  - python-dateutil
  - seaborn
  # tests
  - pytest
  - pytest-json-report
  # dev
  - conda-lock>=0.12
  - pip>=22
  - pip-tools>=6.5
  - setuptools>=61
  # docs
  - autodocsumm
  - myst-parser
  - nbsphinx
  - sphinx-book-theme>=0.3
  - sphinx-gallery==0.9.0
  - sphinx>=3.1
  - sphinxcontrib-bibtex>=2.0
  - sphinx-autobuild
  - sphinx-click>=3.0.2
  - sphinx-copybutton
  - sphinx-design
