channels:
  - eradiate
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  # main
  - aabbtree
  - attrs
  - click
  - cerberus
  - dask
  - matplotlib
  - netcdf4
  - numpy
  - pint
  - ruamel.yaml
  - scipy
  - tinydb
  - tqdm
  - xarray
  # tests
  - pytest
  - pytest-json-report
  - pytest-metadata
  - pytest-xdist
  - sphinx
  - tabulate
  # dev
  - black
  - bump2version
  - conda-lock
  - ipython
  - ipywidgets
  - isort
  - jupyterlab
  - pip
  - pip-tools
  - setuptools
  - twine
  # docs
  - mock
  - nbsphinx
  - pydata-sphinx-theme
  - sphinx>=3.1
  - sphinxcontrib-bibtex<2.0
  - sphinx-copybutton
  - sphinx-panels
