channels:
  - eradiate
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # main
  - aabbtree
  - aenum
  - astropy
  - attrs
  - click
  - cerberus
  - dask
  - dessinemoi>=22.2.0
  - environ-config
  - iapws
  - matplotlib
  - netcdf4
  - numpy
  - pint
  - pinttrs>=21.3.0
  - pooch
  - python-dateutil
  - rich
  - ruamel.yaml
  - scipy
  - seaborn
  - tqdm
  - xarray>=0.19,!=0.20.*
  # tests
  - pytest
  - pytest-json-report
  - pytest-metadata
  - pytest-xdist
  # dev
  - black
  - conda-lock>=0.12
  - coverage
  - ipython
  - ipywidgets
  - isort
  - jupyterlab
  - pip
  - pip-tools>=6.5
  - setuptools>=61
  - setuptools-scm>=6.2
  - twine
  # docs
  - autodocsumm
  - mock
  - myst-parser
  - nbsphinx
  - sphinx-book-theme>=0.1.10
  - sphinx>=3.1
  - sphinxcontrib-bibtex>=2.0
  - sphinx-autobuild
  - sphinx-click>=3.0.2
  - sphinx-copybutton
  - sphinx-design
