# This is a basic CI pipeline, which will build eradiate and
# run the test suite on it.
name: Eradiate build and test

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - github-actions_update-and-tests

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.ERADIATECI_PAT }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          activate-environment: eradiate
      - name: Cache Mitsuba
        uses: actions/cache@v2
        with:
          path: build
          key:
            conda-${{ runner.os }}-${{ runner.arch }}-${{hashFiles('ext/mitsuba') }}-${{ env.CACHE_NUMBER}}
        env:
          CACHE_NUMBER: 0
        id: cache
      - name: Build and run tests
        shell: bash -l {0}
        run: |          
          sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y   \
          git              \
          ninja-build      \
          clang-11          \
          libc++-11-dev     \
          libc++abi-11-dev  \
          libpng-dev       \
          zlib1g-dev       \
          build-essential  \
          libjpeg-dev      \
          ninja-build      \
          cmake

          cmake --version
          
          export CC=clang-11
          export CXX=clang++-11

          cmake --preset default
          cmake --build build
          python -c "import drjit; import mitsuba; mitsuba.set_variant('scalar_rgb')"
        if: steps.cache.outputs.cache-hit != 'true'
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: mitsuba
      #     path: build
      #     retention-days: 5
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.ERADIATECI_PAT }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          activate-environment: eradiate
      # - uses: actions/download-artifact@master
      #   with:
      #     name: mitsuba
      #     path: build
      - name: Cache Mitsuba
        uses: actions/cache@v2
        with:
          path: build
          key:
            conda-${{ runner.os }}-${{ runner.arch }}-${{hashFiles('ext/mitsuba') }}-${{ env.CACHE_NUMBER}}
        env:
          CACHE_NUMBER: 0
        id: cache
      - name: run tests
        shell: bash -l {0}
        run: |
          export CUDA_VISIBLE_DEVICES=""
          make conda-init
          conda deactivate
          conda activate eradiate
          make test
      - name: archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test_results
          path: build/test_artefacts
          retention-days: 5