# This action lints our codebase
name: Eradiate lint

on:
  pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Lint
        run: ruff check --output-format=github
      - name: Format
        if: "!cancelled()"  # Run even if lint fails
        run: ruff format --check
